export const utmKeys = [
  "utm_source",
  "utm_source_type",
  "utm_medium",
  "utm_campaign",
  "utm_campaign_name",
  "utm_region_name",
  "utm_term",
  "utm_content",
  "utm_placement",
  "utm_position",
  "utm_position_type",
  "utm_device",
  "yclid",
];
